-- FOURTH FILE

SELECT DISTINCT
    PERSON.PERSON_IC_NUM,
    CUSTOMER.CUSTOMER_TOTAL_SPENT,
    FRANCHISE.FRANCHISE_ID,
    PRODUCT.PRODUCT_AVAILABILITY,
    ASSET.ASSET_CATEGORY,
    FEEDBACK.FEEDBACK_SERVICERATING,
    PROMOTION.PROMOTION_NAME,
    DRINK.DRINK_ID
FROM PERSON
    LEFT JOIN EMPLOYEE ON Person.PERSON_IC_NUM = Employee.PERSON_IC_NUM
    JOIN CUSTOMER ON Person.Person_IC_Num = Customer.Person_IC_Num
    JOIN CUSTOMER_PROMOTION ON CUSTOMER.CUSTOMER_ID = CUSTOMER_PROMOTION.CUSTOMER_ID
    JOIN PROMOTION ON PROMOTION.PROMOTION_ID = CUSTOMER_PROMOTION.PROMOTION_ID
    JOIN PERSON_PRODUCT ON PERSON.PERSON_IC_NUM = PERSON_PRODUCT.PERSON_IC_NUM
    JOIN PRODUCT ON PERSON_PRODUCT.PRODUCT_ID = PRODUCT.PRODUCT_ID
    JOIN PERSON_ASSET ON PERSON.PERSON_IC_NUM = PERSON_ASSET.PERSON_IC_NUM
    JOIN ASSET ON PERSON_ASSET.ASSET_ID = ASSET.ASSET_ID
    JOIN PERSON_FRANCHISE ON PERSON_FRANCHISE.PERSON_IC_NUM = PERSON.PERSON_IC_NUM
    JOIN FRANCHISE ON FRANCHISE.FRANCHISE_ID = PERSON_FRANCHISE.FRANCHISE_ID
    JOIN PERSON_FEEDBACK ON PERSON.PERSON_IC_NUM = PERSON_FEEDBACK.PERSON_IC_NUM
    JOIN FEEDBACK ON FEEDBACK.FEEDBACK_ID = PERSON_FEEDBACK.FEEDBACK_ID
    JOIN PRODUCT_FRANCHISE ON FRANCHISE.FRANCHISE_ID = PRODUCT_FRANCHISE.FRANCHISE_ID
    JOIN PRODUCT ON PRODUCT_FRANCHISE.PRODUCT_ID = PRODUCT.PRODUCT_ID
    JOIN PRODUCT_PROMOTION ON PRODUCT.PRODUCT_ID = PRODUCT_PROMOTION.PRODUCT_ID
    JOIN PROMOTION ON PRODUCT_PROMOTION.PROMOTION_ID = PROMOTION.PROMOTION_ID
    JOIN FEEDBACK_PROMOTION ON FEEDBACK.FEEDBACK_ID = FEEDBACK_PROMOTION.FEEDBACK_ID
    JOIN PROMOTION ON FEEDBACK_PROMOTION.PROMOTION_ID = PROMOTION.PROMOTION_ID
    JOIN FEEDBACK_PRODUCT ON FEEDBACK.FEEDBACK_ID = FEEDBACK_PRODUCT.FEEDBACK_ID
    JOIN PRODUCT ON FEEDBACK_PRODUCT.PRODUCT_ID = PRODUCT.PRODUCT_ID
    JOIN FEEDBACK_FRANCHISE ON FEEDBACK.FEEDBACK_ID = FEEDBACK_FRANCHISE.FEEDBACK_ID
    JOIN FRANCHISE ON FEEDBACK_FRANCHISE.FRANCHISE_ID = FRANCHISE.FRANCHISE_ID
    JOIN DRINK ON PRODUCT.PRODUCT_ID = DRINK.PRODUCT_ID
WHERE CUSTOMER.CUSTOMER_TOTAL_SPENT > 80
AND FEEDBACK.FEEDBACK_SERVICERATING < 5.0
AND PRODUCT.PRODUCT_AVAILABILITY = 'Available'
AND ASSET.ASSET_CATEGORY = 'Furniture'
ORDER BY CUSTOMER.CUSTOMER_TOTAL_SPENT DESC;